USE BDPROJETO05;

INSERT INTO FORNECEDOR(NOME, CNPJ)
VALUES('Loja de Informatica', '38.061.134/0001-95');

INSERT INTO FORNECEDOR(NOME, CNPJ)
VALUES('Loja de Games', '79.457.769/0001-93');

SELECT * FROM FORNECEDOR;

SELECT * FROM PRODUTO;

INSERT INTO PRODUTO(NOME, PRECO, QUANTIDADE, IDFORNECEDOR)
VALUES('Notebook Dell', 3000, 10, 1);

INSERT INTO PRODUTO(NOME, PRECO, QUANTIDADE, IDFORNECEDOR)
VALUES('Impressora HP', 400, 4, 1);

INSERT INTO PRODUTO(NOME, PRECO, QUANTIDADE, IDFORNECEDOR)
VALUES('Mouse', 30, 10, 1);

CREATE VIEW VW_PRODUTOFORNECEDOR
AS
SELECT 
	P.IDPRODUTO,
    P.NOME,
    P.PRECO,
    P.QUANTIDADE,
    F.IDFORNECEDOR,
    F.NOME AS NOMEFORNECEDOR,
    F.CNPJ
FROM PRODUTO P
INNER JOIN FORNECEDOR F
ON F.IDFORNECEDOR = P.IDFORNECEDOR;

SELECT * FROM VW_PRODUTOFORNECEDOR;

