CREATE DATABASE BDPROJETO05;

USE BDPROJETO05;

CREATE TABLE FORNECEDOR(
	IDFORNECEDOR	INTEGER			AUTO_INCREMENT,
    NOME			VARCHAR(150)	NOT NULL,
    CNPJ			VARCHAR(25)		NOT NULL,
    PRIMARY KEY(IDFORNECEDOR));
    
CREATE TABLE PRODUTO(
	IDPRODUTO		INTEGER			AUTO_INCREMENT,
    NOME			VARCHAR(150)	NOT NULL,
    PRECO			DOUBLE			NOT NULL,
    QUANTIDADE		INTEGER			NOT NULL,
    IDFORNECEDOR	INTEGER			NOT NULL,
    PRIMARY KEY(IDPRODUTO),
    FOREIGN KEY(IDFORNECEDOR) REFERENCES FORNECEDOR(IDFORNECEDOR));
    
SHOW TABLES;

DESC FORNECEDOR;
DESC PRODUTO;